CREATE TABLE side_t(id INTEGER PRIMARY KEY, k INTEGER, w INTEGER);
INSERT INTO side_t(id,k,w)
  WITH RECURSIVE c(i) AS (SELECT 1 UNION ALL SELECT i+1 FROM c WHERE i<10000)
  SELECT i, (i*7919)%1000, (i*31)%4096 FROM c;
SELECT count(*), sum(w) FROM side_t;
