#!/bin/sh
# Expression-algebra gate: exhaustion of (op × type × type × corner) generated by
# gen_alg.py. 3 comparisons: run zcc↔cc (runtime referee), fold zcc↔cc (const-eval
# referee), fold zcc ↔ fri zcc (fold/runtime commuting diagram INTERNAL to a single
# compiler).
set -e
cd "$(dirname "$0")/.."
# ZCC preset from the env (running in the Linux box, no cargo) — otherwise self-build
if [ -z "$ZCC" ]; then
    cargo build --quiet 2>/dev/null || cargo build
    ZCC=target/debug/zcc
fi
D=$(mktemp -d)
trap 'rm -rf "$D"' EXIT

python3 tests/gen_alg.py "$D"

collect() { # $1=compiler-cmd-prefix  $2=stem  → combined output $D/$2_$3.out
    : > "$D/$2_$3.out"
    for f in "$D"/alg_"$2"_*.c; do
        case "$3" in
            zcc) "$ZCC" "$f" -o "$D/x" ;;
            cc)  cc -std=c89 -w -O0 "$f" -o "$D/x" ;;
        esac
        "$D/x" >> "$D/$2_$3.out"
    done
}

fail=0
for stem in run fold fri; do
    collect _ "$stem" zcc
    collect _ "$stem" cc
    if ! diff -q "$D/${stem}_zcc.out" "$D/${stem}_cc.out" > /dev/null; then
        echo "ALG FAIL: $stem zcc≠cc"
        diff "$D/${stem}_zcc.out" "$D/${stem}_cc.out" | head -10
        fail=1
    fi
done
if ! diff -q "$D/fold_zcc.out" "$D/fri_zcc.out" > /dev/null; then
    echo "ALG FAIL: fold≠runtime internal to zcc (commuting diagram broken)"
    diff "$D/fold_zcc.out" "$D/fri_zcc.out" | head -10
    fail=1
fi
n=$(wc -l < "$D/run_zcc.out" | tr -d ' ')
[ "$fail" = 0 ] && echo "ALG PASS ($n runtime points + $(wc -l < "$D/fold_zcc.out" | tr -d ' ') fold points, 4 comparisons)" || exit 1
