#!/bin/sh
# decay gate: the lvalue-conversion theorem C99 6.3.2.1p3 (+6.5.15, 6.5.2.2p6) —
# structural exhaustion of SOURCES × CONTEXTS generated by gen_decay.py, differential
# oracle cc over derived observables (raw addresses are not printed, so the diff is
# stable).
# Motivated by a defect where a ternary string literal failed to decay → vararg
# stack truncated by a 2-byte strh → layout-dependent segv. That cell now has a
# gate standing permanent guard.
set -e
cd "$(dirname "$0")/.."
# ZCC preset from the env (running in the Linux box, no cargo) — otherwise self-build
if [ -z "$ZCC" ]; then
    cargo build --quiet 2>/dev/null || cargo build
    ZCC=target/debug/zcc
fi
D=$(mktemp -d)
trap 'rm -rf "$D"' EXIT

python3 tests/gen_decay.py "$D"

"$ZCC" "$D/decay_t.c" -o "$D/dz"
cc -std=c99 -w -O0 "$D/decay_t.c" -o "$D/dc"
"$D/dz" > "$D/out_zcc.txt"
"$D/dc" > "$D/out_cc.txt"
# CLEAN-INPUT LAW (MECHANISM.md Part A): two EMPTY outputs also compare equal.
# If the generator ever stops emitting observations — a rewrite, a silent Python
# failure, a filter that matches nothing — this gate would print PASS while
# testing zero lvalue conversions. The count is what makes the verdict evidence.
N=$(wc -l < "$D/out_cc.txt" | tr -d ' ')
if [ "$N" -eq 0 ]; then
    echo "DECAY FAIL: the generator produced NO observation — nothing was compared"
    exit 1
fi
if diff -u "$D/out_cc.txt" "$D/out_zcc.txt" > "$D/d.txt"; then
    echo "DECAY PASS ($N differential lines match)"
else
    head -40 "$D/d.txt"
    echo "DECAY FAIL"
    exit 1
fi
